### ISSUE TITLE
BasicHistoryApi

### ISSUE THREAD

**Issue by dahel** [googlesamples/android-fit#10]
Hi,
I'm trying to connecto to google fit using BasicHistoryApi Sample app, but im getting error:
```
Connection failed. Cause: ConnectionResult{statusCode=SIGN_IN_REQUIRED
```

I've added SHA1 from my debug.keystore using
`-exportcert -alias androiddebugkey -keystore debug.keystore -list -v`
I've added it to my fingerprint list in google developer console.
I've enabled Fitness api.

After launching app there is a modal asking for connecting to account, i've selected it.
And still getting this error.

I hope i'm just missing something, and it's not an issue indeed,
will be grateful for any tip

**Comment by PaulRashidi** [comment]
Please confirm you added your Package name and SHA1 to a Google Cloud Console project that has proper consent screen information filled out. After you select the Google Account Google Play services constructs an OAuth2 consent screen based on that registered information and if it can't be found it will look like a SIGN_IN_REQUIRED error.

**Comment by PaulRashidi** [comment]
Please re-open if that wasn't the resolution.

**Comment by dahel** [comment]
Yes, it works now, thanks!
