### ISSUE TITLE
Calories Expended from Sensors API No DataSources available

### ISSUE THREAD

**Issue by RyanNewsom** [googlesamples/android-fit#11]
I am working on an application that we are porting over to use your API. I am having no troubles getting DISTANCE_DELTA to come though and give me 2 DataSource's. But when I try to get calories expended I am getting back  0 DataSource's.

**Comment by RyanNewsom** [comment]
I am reopening this because it seems I am not the only one with this issue, and I have tried a lot to get this to work. Might be a defect?

**Comment by RyanNewsom** [comment]
Cmon, I need some insight on this. This looks like a defect in the API. Can someone please pop in to help =)

**Comment by RyanNewsom** [comment]
More of a feature request. But it does look like you can do it based off the API. I think it would be a nice feature to add.

**Comment by npb12** [comment]
Did anything of come of this?
