### ISSUE TITLE
Exception while connecting to google play services: null

### ISSUE THREAD

**Issue by PadaliaRushabh** [googlesamples/android-fit#15]
Getting Exception "Google Play services connection failed. Cause: ConnectionResult{statusCode=CANCELED, resolution=null, message=null}" when trying to add a google acount.

**Comment by PadaliaRushabh** [comment]
opps, I had forgotten to enable the API.

**Comment by dehamzah** [comment]
@PadaliaRushabh What did you forgot? i have same problem

**Comment by ysq1051838264** [comment]
How to enable the API ?

**Comment by ysq1051838264** [comment]
@PadaliaRushabh  How to enable the API ?

**Comment by chaudharybharat** [comment]
Hello i aslo same got error in relase apk  i had apply  release certificate on google console but still yet got same error 
 only one device inside working 
have any idea plz give me
