### ISSUE TITLE
BasicHistorySessions: Request Fine Location Permissions isn't shown

### ISSUE THREAD

**Issue by cmunter** [googlesamples/android-fit#16]
Shouldn't BasicHistorySessions manifest include:
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`
Otherwise Request Permissions isn't shown

**Comment by colinrtwhite** [comment]
The example doesn't have any permissions requested in its manifest. Really it should contain:

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.INTERNET"/>

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
