### ISSUE TITLE
Sample build fails due to missing dependency

### ISSUE THREAD

**Issue by lichtenw** [googlesamples/android-fit#2]
Unable to build the basic sensors sample due to a missing dependency.  I'm new to gradle so I don't know how to fix the build issue.  

Pre-requisites says:

- Android API Level >v9
- Android Build Tools >v19
- Android Support Repository

My environment:

Android SDK Build-tools: 23.0.5
Android 5.0 (API 21)
Android Support Repository 7
Android Support Library 21
Google Play services 21

Build:

$ gradlew build
Relying on packaging to define the extension of the main artifact has been deprecated and is scheduled to be removed in Gradle 2.0

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services:6.1.+.
     Required by:
         BasicSensorsApi:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.582 secs

**Comment by keyboardsurfer** [comment]
Please install the Google Repository and perform updates from within the SDK Manager.

Compilation with `./gradlew assembleDebug` works fine.

**Comment by keyboardsurfer** [comment]
Closing this now. Please re-open with more info if the issue persists.
