### ISSUE TITLE
Scope for HealthDataTypes of Google Fit

### ISSUE THREAD

**Issue by ViTVetal** [googlesamples/android-fit#22]
I want read HealthDataTypes (temperature, blood pressure and glucose). Which Scope I must set when create GoogleApiClient?

`.addScope(new Scope(????))`

**Comment by mcpotter** [comment]
I'm curious too. Can anyone shed some light on this? I'm unable to read the data (it just gives me "Application needs OAuth consent from the user" because we don't have the required Scope specified, if such a Scope exists).

**Comment by mohananr-tpvision** [comment]
addScope(new Scope("https://www.googleapis.com/auth/fitness.blood_pressure.read")) works. This atleast helps you resolve the "Application needs OAuth consent from the user".  I really dont have an app or a device that would sync HealthData (BP or glucose) into google fit. So, im not able to test anything.
Do you know if there is a device or app in the market that would write healthdata into google fit ?

**Comment by mohananr-tpvision** [comment]
You can also refer to my stackoverfloww link on the same topic.
https://stackoverflow.com/questions/46110711/google-fit-rest-api-support-for-new-healthdatatypes?noredirect=1#comment79232750_46110711

**Comment by FalmaJeus** [comment]
Hello, Have you found any apps that write blood pressure data.
https://play.google.com/store/apps/details?id=com.getqardio.android&hl=en
Please try this qardio app. They say that this app syncs data with Google fit and it has option to input blood pressure manually.
I am not sure that it actually writes data or not.
I had made manual blood pressure data and tried to read /datasources with google fit rest api, but it returns empty array. Of course, the request is authorized.
Please help me if you can.
Thanks.

**Comment by ViTVetal** [comment]
@FalmaJeus Hello! Unfortunately, I didn't find the solution. You may write do developers of this app on play store

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
