### ISSUE TITLE
Authen to google problem

### ISSUE THREAD

**Issue by tntkhang** [googlesamples/android-fit#23]
When I run app the pop-up select email to authen to Google, I select the email but the app always throw StatusCode = CANCEL. Does the authen funtion out of date ? Do we need to switch to this authen guide: https://developer.android.com/training/wearables/apps/auth-wear.html#configure-google-sign-in

**Comment by Kagetsuki** [comment]
I'm having the same issue, did you ever figure it out?

**Comment by yoshimaa** [comment]
@tntkhang  @Kagetsuki 
this android-fit sample is not so good, anynone fix that problem.

**Comment by Kagetsuki** [comment]
I ended up using a bunch of different guides. Everything from Google is outdated. The permission names are different, you have to ask for permission with a method at run-time, a bunch of the method names have changed. The library version in samples is 3 major versions out of date. If Google is wondering why there's so few apps with Google Fit integration - this is the reason why.Your official documentation and samples are garbage.

**Comment by thisisjatinrana** [comment]
Check if internet connectivity is there. I was facing same issue later found out that wifi was off.

**Comment by paul-ridgway** [comment]
Make sure you have associated an OAuth 2.0 client id with your keystore - https://developers.google.com/fit/android/get-api-key

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
