### ISSUE TITLE
Data differs from the actual Google Fit App

### ISSUE THREAD

**Issue by sushantgiri** [googlesamples/android-fit#25]
I am building a fitness application where I pull certain data (Steps and Calories) from google fit. I am fetching a week data. The output of the google fit api doesn't match with the google fit data. The output is so random and doesn't have a definite pattern.

Steps From Google Fit API:
**Code Used:**
private DataReadRequest queryFitnessData()
{
Calendar cal = Calendar.getInstance();
Date now = new Date();
cal.setTime(now);
long endTime = cal.getTimeInMillis();
cal.add(Calendar.WEEK_OF_YEAR, -1);
long startTime = cal.getTimeInMillis();
java.text.DateFormat dateFormat = getDateInstance();
Timber.e("Range Start: " + dateFormat.format(startTime));
Timber.e("Range End: " + dateFormat.format(endTime));
return new DataReadRequest.Builder()
.aggregate(DataType.TYPE_STEP_COUNT_DELTA, DataType.AGGREGATE_STEP_COUNT_DELTA)
.bucketByTime(1, TimeUnit.DAYS)
.setTimeRange(startTime, endTime, TimeUnit.MILLISECONDS)
.build();
}

public Observable getStepsCount(GoogleApiClient googleApiClient) {
return Observable.create(subscriber -> {
DataReadResult result =
Fitness.HistoryApi.readData(googleApiClient, queryFitnessData()).await(1, TimeUnit.MINUTES);
if (result.getStatus().isSuccess()) {
subscriber.onNext(result);
} else {
subscriber.onError(new Exception("Exception"));
}
});
}

**Output**
Start Date: 17th August 2017           End Date: 24th August 2017

17-18 -> 4080
18-19 -> 3837
19-19 -> 7
20-21 -> 2212
21-22 -> 4665
23-23 -> 2949
23-24 -> 6131

Any help would be greatly appreciated. If required, apk can also be shared.

**Comment by yoshimaa** [comment]
@sushantgiri 
check this documents.
https://developers.google.com/fit/faq#get-step-count
not always match.

**Comment by joostfunkekupper** [comment]
I found that when requesting DataSets from the HistoryAPI work best when supplying the date and time at the start of a day (midnight). It would then return the buckets with more reliable data. Every time the data was refreshed the times were shifted because the examples use `Date now = new Date()` which of course is different each time.
(I used JodaTime to simplify the start and end times)

```
// Setting a start and end date using a range of 1 week working backwards using today's
// start of the day (midnight). This ensures that the buckets are in line with the days.
DateTime dt = new DateTime().withTimeAtStartOfDay();
long endTime = dt.getMillis();
long startTime = dt.minusWeeks(1).getMillis();

return new DataReadRequest.Builder()
        .aggregate(DataType.TYPE_STEP_COUNT_DELTA, DataType.AGGREGATE_STEP_COUNT_DELTA)
        .bucketByTime(1, TimeUnit.DAYS)
        .setTimeRange(startTime, endTime, TimeUnit.MILLISECONDS)
        .build();
```

Without setting the time to the start of the day:
![screenshot_20180305-152838](https://user-images.githubusercontent.com/1082672/36957730-8d279d50-208a-11e8-8879-f4908388c06e.png)

With setting the time to the start of the day:
![screenshot_20180305-152752](https://user-images.githubusercontent.com/1082672/36957732-967a364c-208a-11e8-9a43-41fecd4c4804.png)

**Comment by rduvvu** [comment]
Hi joostfunkekupper ,

Can u please share your code.

Thankyou

**Comment by joostfunkekupper** [comment]
Hi @rduvvu 
Yeah sure, I haven't run it since March 2018, but should be fine still.
Just uploaded it to a new public repo https://github.com/joostfunkekupper/google-fit-android
Cheers

**Comment by rduvvu** [comment]
Hi  Joost Funke Kupper,

Thank you so much for your response.But I haven't  got the steps count
Values It would be more helpful if your resolve this issue

ThankYou.

**Comment by joostfunkekupper** [comment]
@rduvvu I'm not a contributor to this repository, and probably don't have the time right now to make a PR. As @yoshimaa said, the Google Fit app will always result in slightly different values anyway; https://developers.google.com/fit/faq#get-step-count
To me it sounds like you have a different issue not related to this issue [#25](https://github.com/googlesamples/android-fit/issues/25)

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
