### ISSUE TITLE
Missing sample of BroadcastReceiver for Session Start/End

### ISSUE THREAD

**Issue by rubinbasha** [googlesamples/android-fit#30]
"Google Fit broadcasts intents when any app starts or stops recording a session on behalf of the user. Fitness apps can register a listener to receive these intents."

Can we please have a sample of that? I am trying to implement one myself but not being able to receive intents right now and having a sample would be very helpful. 

Kind regards,
Rubin

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
