### ISSUE TITLE
couldnt get account info

### ISSUE THREAD

**Issue by saravanan72** [googlesamples/android-fit#31]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.accounts.Account com.google.android.gms.auth.api.signin.GoogleSignInAccount.getAccount()' on a null object reference

error caught in step counter

**Comment by stAyushJain** [comment]
you need to register your SHA1 fingerprint. [
Get an OAuth 2.0 Client ID](https://developers.google.com/fit/android/get-api-key)

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
