### ISSUE TITLE
sphal namespace is not configured for this process.

### ISSUE THREAD

**Issue by ankitaturani573** [googlesamples/android-fit#32]
I am trying to run the BasicSensorsApi code but getting this error after choosing the gmail account.
I am using an Android Oreo One PLus5.

This is the error I am getting.

04-01 01:30:26.680 26997-26997/com.google.android.gms.fit.samples.basicsensorsapi D/AppTracker: App Event: stop
04-01 01:30:26.717 26997-27076/com.google.android.gms.fit.samples.basicsensorsapi I/Adreno: QUALCOMM build                   : d52c199, I26dffed9a4
                                                                                            Build Date                       : 01/09/18
                                                                                            OpenGL ES Shader Compiler Version: EV031.22.00.01
                                                                                            Local Branch                     : 
                                                                                            Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.4.R1.08.00.00.309.052
                                                                                            Remote Branch                    : NONE
                                                                                            Reconstruct Branch               : NOTHING
04-01 01:30:26.717 26997-27076/com.google.android.gms.fit.samples.basicsensorsapi I/vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8998.so from the current namespace instead.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
