### ISSUE TITLE
Signed APK doesn't  show subsription page.

### ISSUE THREAD

**Issue by saravanan72** [googlesamples/android-fit#35]
Hi,
I have tried this google fitness API as a sample one. When i am getting apk in debug format, it run perfectly .When i run this , initially it subscribe by using gmail account and provides step count value as i expect. But when i try with signed APK, its doesn't work. It doesn't show the subscription dialog and also the count doesn't show without subscription. Please give solution regarding that. Thanks.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
