### ISSUE TITLE
Unable to remove the listener from the SensorsApi.

### ISSUE THREAD

**Issue by lifeLessCoder** [googlesamples/android-fit#36]
I'm not able to remove the listener from SensorsApi. After the remove(mListener) method is called, task.getResult() returns false in the OnComplete method.

**Comment by casman51** [comment]
> I'm not able to remove the listener from SensorsApi. After the remove(mListener) method is called, task.getResult() returns false in the OnComplete method.

Hey man I have the same problem, already got it working?

**Comment by lifeLessCoder** [comment]
@casman51 as of now I've created an issue in Google's issue tracker. You can go to below link and star it so that it gets fixed quickly. 
https://issuetracker.google.com/issues/130741650

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
