### ISSUE TITLE
How to debug sessions/activities in real time without delay until data updates in Google fit app

### ISSUE THREAD

**Issue by pavelpoley** [googlesamples/android-fit#39]
How to debug in real time sessions/activities (data insertion), it is take hours until the data shows in Google fit app, sometimes it does not show all, even when onSuccess and onComplete called, very hard to test with this delays.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
