### ISSUE TITLE
Non existent function -_-

### ISSUE THREAD

**Issue by kienme** [googlesamples/android-fit#4]
"Cannot resolve method setActivity(java.lang.String)"

BasicHistorySession: MainActivity.java: lines 338, 343, 348

Its not even there in the documentation!

**Comment by joannasmith** [comment]
The [setActivity() method](http://developer.android.com/reference/com/google/android/gms/fitness/data/Value.html#setActivity(java.lang.String)) was added to `Value` in Google Play Services v6.5.  You'll need to update Google Play Services to use this.
