### ISSUE TITLE
Values that returned from History API is not the same with Google Fit App

### ISSUE THREAD

**Issue by panjiyudasetya** [googlesamples/android-fit#42]
## What happened

Step count value that I've been received from History API was different with step count values that has been displayed in Fit App. Even problem solving for different values between Fit History Api and Google Fit App has been mentioned [here](https://developers.google.com/fit/faq#values-no-match), sometimes this problem still occurred in certain device.

In my case, I was using : 
- Phone HTC One_E8 dual sim
- Android version 6.0.1
- Google Play services 14.3.66

| Fit API Prober | Fit App |
--- | ---
<img src="https://user-images.githubusercontent.com/21379421/47766369-d9495380-dd00-11e8-90b0-c84930b81fa7.png" width="200"> | <img src="https://user-images.githubusercontent.com/21379421/47766374-dd757100-dd00-11e8-971a-e5fcacb89cfa.png" width="200">

As you can see that in Fit API prober, I got **3300 datapoint** for today step count, meanwhile in Fit App, **2433 datapoint** has been displayed. The margin is quite huge in this case.

## What was expected
History API return same value with Google Fit App.

## Code Snippets

As for addition, both approach are returning **3300 datapoint** rather than **2433 datapoint**.
<details>
 <summary>History API today step count</summary>

```java
        Fitness.getHistoryClient(mContext, GoogleSignIn.getLastSignedInAccount(mContext))
            .readDailyTotal(DataType.TYPE_STEP_COUNT_DELTA)
            .addOnSuccessListener(new OnSuccessListener<DataSet>() {
                @Override
                public void onSuccess(DataSet dataSet) {
                    int totalStepCount = extractHistoryFromDataSet(dataSet);
                    callback.onResult(totalStepCount);
                }
            })
            .addOnFailureListener(new OnFailureListener() {
                @Override
                public void onFailure(@NonNull Exception e) {
                    callback.onError(e.getMessage());
                }
            });
```
</details>
<details>
<summary>History API through step count aggregation</summary>

```java

DataSource getFitStepCountDataSource() {
        return new DataSource.Builder()
                .setDataType(DataType.TYPE_STEP_COUNT_DELTA)
                .setType(DataSource.TYPE_DERIVED)
                .setStreamName("estimated_steps")
                .setAppPackageName("com.google.android.gms")
                .build();
}

Task<DataReadResponse> readHistory(long startTime, long endTime) {
        DataReadRequest request = new DataReadRequest.Builder()
            .aggregate(getFitStepCountDataSource(), DataType.AGGREGATE_STEP_COUNT_DELTA)
            .bucketByTime(1, TimeUnit.DAYS)
            .setTimeRange(startTime, endTime, TimeUnit.MILLISECONDS)
            .enableServerQueries()
            .build();
        return Fitness.getHistoryClient(mContext, GoogleSignIn.getLastSignedInAccount(mContext))
            .readData(request);
}
```
</details>

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
