### ISSUE TITLE
Error: No permission to read data for this private data source.

### ISSUE THREAD

**Issue by Zaszczyk** [googlesamples/android-fit#43]
I use Google Fit REST API for over 2 years and everything was fine already. However since 20th November I am occuring the only reply on route: 

> /me/dataSources/derived:com.google.location.sample:com.google.android.gms:merge_high_fidelity/datasets/

```
( 'domain' => 'global', 
'reason' => 'forbidden', 
'message' => 'No permission to read data for this private data source.', )
```
I had not changed anything in my code, did Google change something?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
