### ISSUE TITLE
is there any way to get the actual create time for a session?

### ISSUE THREAD

**Issue by zjx** [googlesamples/android-fit#46]
looks like the fit system will use the end time as the "timestamp" field which may not be the actual create time of a session. For example,

a running session may happened from 13:00 to 14:00 on a third party app but the actual sync to google fit happens on 18:00 triggered by user manually.

my app just want to retrieve the New Sessions since the last read but if can not get the actual create time in the google fit then there is no way to do this?

any suggestions? Thx.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
