### ISSUE TITLE
DataSourceListener, where is this class?

### ISSUE THREAD

**Issue by josemg08** [googlesamples/android-fit#6]
I'm trying to copy the official Google Fit sample from here https://www.youtube.com/watch?v=jwaQaWGLlTo#t=178. I'm having problems with the `DataSourceListener`. When I try to add that class in AndroidStudio it doesn't seem to find it, the class doesn't seem to exist...

**Comment by joannasmith** [comment]
`DataSourceListener` was migrated to `OnDataPointListener` in Google Play Services v6.1.84. See the diff in this [commit](https://github.com/googlesamples/android-fit/commit/28f00c1f688a547cf462fe1d63cfd796e9cfb400#diff-5689b0d33c75e07d7fa692390280360d) from October 21, 2014.
