### ISSUE TITLE
Google Account Sign_IN_FAILED

### ISSUE THREAD

**Issue by felon124** [googlesamples/android-fit#7]
I used these sample and found that I couldn't login.  

Error Message :
Connection failed. Cause: ConnectionResult{statusCode=SIGN_IN_FAILED, resolution=null}

I don't know how to fix it.

**Comment by felon124** [comment]
Sorry , I found that I forgot setting up OAuth 2.0.
The sample is working now.

**Comment by madhavajay** [comment]
How did you setup oauth2?

**Comment by ad-on-is** [comment]
I'm having exactly the same problem now. How do I setup oAuth 2.0? I followed the instructions on the getting-started guide but it doesn't work.

**Comment by ad-on-is** [comment]
OK, got it... in the OAuth Settings I had to fill in the full packagename. I only had the first part.
wrong: com.example
right: com.example.myapp

**Comment by madhavajay** [comment]
Yeah I finally figured it out too, but I dont understand, the permissions are buggy.
Firstly, if I auth the app and then go to the Google Play Settings and then to Google Fit Apps, sometimes my app isnt in there, and then it appears later.

Secondly and more importantly, theres no callback for when you successfully auth the permissions. So I have a button which attempts a connect and then it launches the auth view after failure, but once I approve the permissions nothing is called, so I have to re-attempt to auth. Does anyone have a better idea on how this flow is supposed to be handled?

**Comment by Shahroz16** [comment]
Guys can you guide me here, i must be missing something right infront of me but i can't find 
OAuth settings to change package name. :S 
Help me out here, facing the same issue as you guys.

**Comment by Shahroz16** [comment]
NeverMind got it :dancer:

**Comment by mootoh** [comment]
@Shahroz16, I think you would like to follow the steps in https://developers.google.com/fit/android/get-started for OAuth stuff.
