### ISSUE TITLE
keep getting SIGN_IN_FAILED when requesting history data in my own app.

### ISSUE THREAD

**Issue by eggman87** [googlesamples/android-fit#8]
Do we need to include the api key? If so what is the name of it in the meta data tag.

**Comment by RyanNewsom** [comment]
I am seeing this same issue. What did you do to resolve this issue? @eggman87 
:question:

**Comment by eggman87** [comment]
@RyanNewsom I honestly can not remember. I closed it because it was something obvious but not well documented. 

Make sure you have oauth credentials setup in the api console. 
Make sure you also have enabled fitness api. 

https://support.google.com/cloud/answer/6158857?hl=en

**Comment by RyanNewsom** [comment]
Thanks, I actually got it working right after I asked you.
:+1:

**Comment by PaulRashidi** [comment]
Make sure your Consent Screen is also configured within your Cloud project as well as the packageName and SHA1 for the cert you're using are also registered (even if just building a debug build).  I don't believe the API key needs to be specified for FIT, but it is used for Maps.

**Comment by RyanNewsom** [comment]
I said I had it working, but thank you!

**Comment by PaulRashidi** [comment]
Yep, saw that @RyanNewsom Just wanted to log some resolution steps for others that stumbled upon this issue (like you did).
